# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('phone', models.IntegerField()),
                ('emp_id', models.IntegerField()),
            ],
        ),
    ]
